name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.
on:
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks out the repo so the action can access it
      - uses: actions/checkout@v2

      # Generates the snake GIF and SVG based on the contributions
      - uses: Platane/snk@v1.0.0  # Use a stable version of Platane/snk
        id: snake-gif
        with:
          github_user_name: emir-efe
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Show the status of the build (for debugging)
      - run: git status

      # Push the generated files to the output branch
      - name: Push changes to output branch
        uses: ad-m/github-push-action@v0.6.0  # Use a stable version of the push action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output  # Pushing to the output branch, not master
          force: true

      # Deploy to GitHub Pages from the output branch
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output  # The output branch for GitHub Pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
